//
//  HomeRouter.swift
//  ALojinha
//
//  Created by Arlen Ricardo Pereira on 01/05/19.
//  Copyright (c) 2019 Arlen Ricardo Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic
{
  func routeToProductList(segue: UIStoryboardSegue?)
  func routeToProductDetail(segue: UIStoryboardSegue?)
}

protocol HomeDataPassing
{
  var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing
{

  weak var viewController: HomeViewController?
  var dataStore: HomeDataStore?
  
  // MARK: - Routing
  func routeToProductList(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
        let destinationVC = segue.destination as! ProductListViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToProductList(source: dataStore!, destination: &destinationDS)
    } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "ProductListViewController") as! ProductListViewController
        
    var destinationDS = destinationVC.router!.dataStore!
    passDataToProductList(source: dataStore!, destination: &destinationDS)
    navigateToProductList(source: viewController! , destination: destinationDS as! ProductListViewController)
    }
  }

  // MARK: - Navigation
  func navigateToProductList(source: HomeViewController, destination: ProductListViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: - Passing data
  func passDataToProductList(source: HomeDataStore, destination: inout ProductListDataStore)
  {
    let categorySelect = viewController?.collectionViewFrame.indexPathsForSelectedItems?.first
    let temp = categorySelect?.row
    let category2 = source.categories?[temp!]
    destination.category = [category2] as? [CategoryAPIRequest]
    }
    
    // MARK: - Routing
    func routeToProductDetail(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! ProductDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToProductDetail(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "ProductDetailViewController") as! ProductDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToProductDetail(source: dataStore!, destination: &destinationDS)
            navigateToProductDetail(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: - Navigation
    func navigateToProductDetail(source: HomeViewController, destination: ProductDetailViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: - Passing data
    func passDataToProductDetail(source: HomeDataStore, destination: inout ProductDetailDataStore)
    {
        let selected = viewController?.tableViewFrame.indexPathForSelectedRow?.row
        let productSelected = source.product?[selected!]
        destination.productDetail = productSelected
    }
}
