//
//  HomeModels.swift
//  ALojinha
//
//  Created by Arlen Ricardo Pereira on 01/05/19.
//  Copyright (c) 2019 Arlen Ricardo Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum HomeModel
{
  // MARK: - Banner Models
  enum BannerModel
  {
    struct Request
    {
    }
    struct Response
    {
        var bannersResponse: [BannerAPIRequest]
    }
    struct ViewModel
    {
        struct DisplayedBanners {
            var id: Int
            var urlImagem: String
            var linkUrl: String
        }
        var displayersBanner: [DisplayedBanners]
    }
  }
    
    // MARK: - Category Models
    enum CategoriesModel {
        
        struct Request { }
        
        struct Response {
            var categoryResponse: [CategoryAPIRequest]
        }
        
        struct ViewModel {
            struct DisplayedCategories {
                var id: Int
                var description: String
                var urlImagem: String
            }
            var displayersCategory: [DisplayedCategories]
        }
    }
    
    // MARK: - Best Sellers Models
    enum BestSellersModel{
        
        struct Request { }
        
        struct Response {
            var bestSellersResponse: [ProductAPIRequest]
        }
        
        struct ViewModel {
            struct DisplayedBestSellers {
                var categoryDescription: String
                var id: Int
                var name: String
                var urlImagem: String
                var descriptionBS: String
                var price1: Double
                var price2: Double
            }
            var displayersBestSellers: [DisplayedBestSellers]
        }
    }
}
