//
//  HomePresenter.swift
//  ALojinha
//
//  Created by Arlen Ricardo Pereira on 01/05/19.
//  Copyright (c) 2019 Arlen Ricardo Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
  func presentBanners(response: HomeModel.BannerModel.Response)
  func presentCategories(response: HomeModel.CategoriesModel.Response)
  func presentBestSellers(response: HomeModel.BestSellersModel.Response)
}

class HomePresenter: HomePresentationLogic
{
  weak var viewController: HomeDisplayLogic?
  
  // MARK: - Functions
  
  func presentBanners(response: HomeModel.BannerModel.Response)
  {
    var displayedBanners: [HomeModel.BannerModel.ViewModel.DisplayedBanners] = []
    for banner in response.bannersResponse {
        let displayedBanner = HomeModel.BannerModel.ViewModel.DisplayedBanners(id: banner.idBanner, urlImagem: banner.urlImagemBanner, linkUrl: banner.linkUrlBanner)
        displayedBanners.append(displayedBanner)
    }
    
    let viewModel = HomeModel.BannerModel.ViewModel(displayersBanner: displayedBanners)
    viewController?.displayBanners(viewModel: viewModel)
  }
    
    func presentCategories(response: HomeModel.CategoriesModel.Response)
    {
        var displayedCategories: [HomeModel.CategoriesModel.ViewModel.DisplayedCategories] = []
        for category in response.categoryResponse {
            let displayedCategory = HomeModel.CategoriesModel.ViewModel.DisplayedCategories(
                id: category.idCategory,
                description: category.descriptionCategory,
                urlImagem: category.urlImagemCategory)
            
            displayedCategories.append(displayedCategory)
        }
        
        let viewModel = HomeModel.CategoriesModel.ViewModel(displayersCategory: displayedCategories)
        viewController?.displayCategories(viewModel: viewModel)
    }
    
    func presentBestSellers(response: HomeModel.BestSellersModel.Response)
    {
        var displayedBestSellers: [HomeModel.BestSellersModel.ViewModel.DisplayedBestSellers] = []
        for bestSeller in response.bestSellersResponse {
            let displayedBestSeller = HomeModel.BestSellersModel.ViewModel.DisplayedBestSellers(
                categoryDescription: bestSeller.category.descriptionCategory,
                id: bestSeller.idProduct,
                name: bestSeller.nameProduct,
                urlImagem: bestSeller.urlImagemProduct,
                descriptionBS: bestSeller.descriptionProduct,
                price1: bestSeller.price1Product,
                price2: bestSeller.price2Product)
            
            displayedBestSellers.append(displayedBestSeller)
        }
        
        let viewModel = HomeModel.BestSellersModel.ViewModel(displayersBestSellers: displayedBestSellers)
        viewController?.displayBestSellers(viewModel: viewModel)
    }
}
