//
//  ProductDetailsViewControllerTests.swift
//  Lodjinha
//
//  Created by Gilson Gil on 27/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Lodjinha

import Quick
import Nimble

final class ProductDetailsViewControllerSpec: QuickSpec {
  override func spec() {
    let sut = ProductDetailsViewController()
    let name = "Fifa 17"
    let imageUrl = "https://images-submarino.b2w.io/produtos/01/00/item/128926/4/128926443_1GG.png"
    // swiftlint:disable line_length
    let description = "Mussum Ipsum, cacilds vidis litro abertis. Atirei o pau no gatis, per gatis num morreus. Num sou faixa preta cumpadi, sou preto inteiris, inteiris. Praesent malesuada urna nisi, quis volutpat erat hendrerit non. Nam vulputate dapibus. Diuretics paradis num copo é motivis de denguis.<br/><br/>"
    let category = Category(identifier: 1,
                            description: "Games",
                            imageUrl: "http://39ahd9aq5l9101brf3b8dq58.wpengine.netdna-cdn.com/wp-content/uploads/2013/06/3D-Gaming.png")
    // swiftlint:enable line_length
    let fromPrice: Double = 200
    let toPrice: Double = 100
    (sut.interactor as? ProductDetailsInteractor)?.product = Product(identifier: 1,
                                                                     name: name,
                                                                     imageUrl: imageUrl,
                                                                     description: description,
                                                                     fromPrice: fromPrice,
                                                                     toPrice: toPrice,
                                                                     category: category)
    let window = UIWindow()
    window.rootViewController = sut
    window.makeKeyAndVisible()

    describe("given an product details view controller") {
      context("when successfully loaded") {
        it("should display a image cell at row 0") {
          let indexPath = IndexPath(row: 0, section: 0)
          let cell = sut.productDetailsView?.tableView.cellForRow(at: indexPath)
          expect(cell).to(beAnInstanceOf(ProductImageCell.self))
          let imageCell = cell as? ProductImageCell
          expect(imageCell?.nameLabel.text).toEventually(equal(name))
        }

        it("should display a price cell at row 1") {
          let indexPath = IndexPath(row: 1, section: 0)
          let cell = sut.productDetailsView?.tableView.cellForRow(at: indexPath)
          expect(cell).to(beAnInstanceOf(ProductPriceCell.self))
          let priceCell = cell as? ProductPriceCell
          let fromPriceString = String(format: "%@%.2f", arguments: [String.Home.priceFrom, fromPrice])
          let toPriceString = String(format: "%@%.2f", arguments: [String.Home.priceTo, toPrice])
          expect(priceCell?.fromLabel.text).toEventually(equal(fromPriceString))
          expect(priceCell?.toLabel.text).toEventually(equal(toPriceString))
        }

        it("should display a description cell at row 2") {
          let indexPath = IndexPath(row: 2, section: 0)
          let cell = sut.productDetailsView?.tableView.cellForRow(at: indexPath)
          expect(cell).to(beAnInstanceOf(ProductDescriptionCell.self))
        }
      }
    }
  }
}
