# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Challange-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher', '~> 4.0'

  # Pods for Challange-iOS

  target 'Challange-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Challange-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
