//
//  ProductDetailsModels.swift
//  Lodjinha
//
//  Created by Gilson Gil on 25/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductDetails {
  enum DisplayProduct {
    struct Request {
    }
    struct Response {
      let product: Product
    }
    struct ViewModel {
      let displayedProduct: DisplayedProduct
    }
  }

  enum DisplayTitle {
    struct Request {
    }
    struct Response {
      let product: Product
    }
    struct ViewModel {
      let title: String
    }
  }

  enum ReserveProduct {
    struct Request {}
    struct Response {
      let message: String
    }
    struct ViewModel {
      let message: String
    }
  }
}
