//
//  ProductDetailsInteractor.swift
//  Lodjinha
//
//  Created by Gilson Gil on 25/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailsBusinessLogic {
  func getProduct(request: ProductDetails.DisplayProduct.Request)
  func getNavigationTitle(request: ProductDetails.DisplayTitle.Request)
  func didTapReserve(request: ProductDetails.ReserveProduct.Request)
}

protocol ProductDetailsDataStore {
  var product: Product? { get set }
}

final class ProductDetailsInteractor: ProductDetailsBusinessLogic, ProductDetailsDataStore {
  var presenter: ProductDetailsPresentationLogic?
  lazy var worker: ProductDetailsWorker? = { ProductDetailsWorker() }()
  var product: Product?

  func getProduct(request: ProductDetails.DisplayProduct.Request) {
    guard let product = product else { return }
    let response = ProductDetails.DisplayProduct.Response(product: product)
    presenter?.presentProductDetails(response: response)
  }

  func getNavigationTitle(request: ProductDetails.DisplayTitle.Request) {
    guard let product = product else { return }
    let response = ProductDetails.DisplayTitle.Response(product: product)
    presenter?.presentTitle(response: response)
  }

  func didTapReserve(request: ProductDetails.ReserveProduct.Request) {
    guard let identifier = product?.identifier else { return }
    worker?.reserveProduct(with: identifier) { [weak self] callback in
      do {
        _ = try callback()
        let response = ProductDetails.ReserveProduct.Response(message: String.ProductDetails.successMessage)
        self?.presenter?.presentReserveSuccess(response: response)
      } catch {
        self?.presenter?.presentError(error)
      }
    }
  }
}
