//
//  ProductDetailsInteractor.swift
//  Lodjinha
//
//  Created by Gilson Gil on 25/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailsBusinessLogic {
  func getProduct(request: ProductDetails.DisplayProduct.Request)
  func getNavigationTitle(request: ProductDetails.DisplayTitle.Request)
}

protocol ProductDetailsDataStore {
  var product: Product? { get set }
}

final class ProductDetailsInteractor: ProductDetailsBusinessLogic, ProductDetailsDataStore {
  var presenter: ProductDetailsPresentationLogic?
  var worker: ProductDetailsWorker?
  var product: Product?

  func getProduct(request: ProductDetails.DisplayProduct.Request) {
    guard let product = product else { return }
    let response = ProductDetails.DisplayProduct.Response(product: product)
    presenter?.presentProductDetails(response: response)
  }

  func getNavigationTitle(request: ProductDetails.DisplayTitle.Request) {
    guard let product = product else { return }
    let response = ProductDetails.DisplayTitle.Response(product: product)
    presenter?.presentTitle(response: response)
  }
}
