# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Lodjinha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lodjinha
  pod 'RSRealmHelper', '~> 1.0.0'
  #pod 'Alamofire', '~> 4.8.0'
  #pod 'AlamofireObjectMapper', '~> 5.2.0'
  #pod 'ObjectMapper', '~> 3.4.2'
  pod 'RxSwift', '~> 4.4.0'
  pod 'RSReactiveRequest', :git => 'https://github.com/redspark-io/RSReactiveRequest.git'

  target 'LodjinhaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LodjinhaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
