# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lodjinha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher'
  # Pods for Lodjinha

  target 'LodjinhaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
