//
//  HomeViewController.swift
//  Lodjinha
//
//  Created by Gilson Gil on 22/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic: class {
  func displayError(_ error: Error)
  func displayBanners(viewModel: Home.FetchBanner.ViewModel)
}

final class HomeViewController: UIViewController {
  var interactor: HomeBusinessLogic?
  var router: (NSObjectProtocol & HomeRoutingLogic & HomeDataPassing)?
  var homeView: HomeViewLogic?
  var displayedBanners: [Home.FetchBanner.DisplayedBanner]?

  // MARK: - Object lifecycle

  init() {
    super.init(nibName: nil, bundle: nil)
    setup()
  }

  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }

  // MARK: - Setup

  private func setup() {
    let viewController = self
    let interactor = HomeInteractor()
    let presenter = HomePresenter()
    let router = HomeRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor

    let tabBarItem = UITabBarItem(title: String.Home.tabBar,
                                  image: UIImage.Home.tabBarIcon,
                                  selectedImage: UIImage.Home.tabBarIconSelected)
    self.tabBarItem = tabBarItem
  }

  // MARK: - View lifecycle

  override func loadView() {
    let homeView = HomeView()
    self.homeView = homeView
    view = homeView
  }

  override func viewDidLoad() {
    super.viewDidLoad()
    setupTableView()
    fetchBanner()
  }

  override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)

    let image = UIImage.Root.logo
    let imageView = UIImageView(frame: CGRect(origin: .zero, size: image.size))
    imageView.image = image
    parent?.navigationItem.titleView = imageView
  }

  // MARK: - TableView

  func setupTableView() {
    homeView?.tableView.register(HomeBannerCell.self,
                                 forCellReuseIdentifier: HomeBannerCell.reuseIdentifier)
    homeView?.tableView.dataSource = self
    homeView?.tableView.delegate = self
  }

  // MARK: - Fetch Banner

  func fetchBanner() {
    interactor?.fetchBanner()
  }
}

// MARK: - HomeDisplayLogic
extension HomeViewController: HomeDisplayLogic {
  func displayError(_ error: Error) {
    DispatchQueue.main.async {
      let alert = UIAlertController(title: error.localizedDescription, message: nil, preferredStyle: .alert)
      let okAction = UIAlertAction(title: String.Lodjinha.close, style: .default, handler: nil)
      alert.addAction(okAction)
      self.present(alert, animated: true, completion: nil)
    }
  }

  func displayBanners(viewModel: Home.FetchBanner.ViewModel) {
    DispatchQueue.main.async {
      self.displayedBanners = viewModel.displayedBanners
      let firstSection = IndexSet(integer: 0)
      self.homeView?.tableView.reloadSections(firstSection, with: .none)
    }
  }
}

// MARK: - UITableView DataSource
extension HomeViewController: UITableViewDataSource {
  func numberOfSections(in tableView: UITableView) -> Int {
    return 3
  }

  func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    switch section {
    case 0:
      return displayedBanners != nil ? 1 : 0
    default:
      return 0
    }
  }

  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    let cell: UITableViewCell
    switch indexPath.section {
    case 0:
      cell = tableView.dequeueReusableCell(withIdentifier: HomeBannerCell.reuseIdentifier, for: indexPath)
      if let bannerCell = cell as? HomeBannerCellLogic {
        let viewModel = HomeBannerCellViewModel(displayedBanners: displayedBanners ?? [])
        bannerCell.update(viewModel: viewModel)
      }
    default:
      cell = UITableViewCell()
    }
    return cell
  }
}

// MARK: - UITableView Delegate
extension HomeViewController: UITableViewDelegate {
  func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
    switch indexPath.section {
    case 0:
      return 120
    default:
      return 0
    }
  }
}
