//
//  HomeModels.swift
//  Lodjinha
//
//  Created by Gilson Gil on 22/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
  enum FetchBanner {
    struct DisplayedBanner {
      let stringUrl: String
    }

    struct Request {}
    struct Response {
      let banners: [Banner]
    }
    struct ViewModel {
      let displayedBanners: [DisplayedBanner]
    }
  }

  enum PresentBannerLink {
    struct Request {}
    struct Response {
      let banner: Banner
    }
    struct ViewModel {
      let link: String
    }
  }

  enum FetchCategories {
    struct DisplayedCategory {
      let description: String
      let imageUrl: String
    }

    struct Request {}
    struct Response {
      let categories: [Category]
    }
    struct ViewModel {
      let displayedCategories: [DisplayedCategory]
    }
  }

  enum PresentCategory {
    struct Request {}
    struct Response {
      let category: Category
    }
    struct ViewModel {
      let category: Category
    }
  }

  enum FetchBestsellers {
    struct Request {}
    struct Response {
      let products: [Product]
    }
    struct ViewModel {
      let displayedProducts: [DisplayedProduct]
    }
  }

  enum PresentBestsellers {
    struct Request {}
    struct Response {
      let product: Product
    }
    struct ViewModel {
      let product: Product
    }
  }
}
