//
//  HomePresenter.swift
//  Lodjinha
//
//  Created by Gilson Gil on 22/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
  func presentError(_ error: Error)
  func presentBanners(response: Home.FetchBanner.Response)
}

final class HomePresenter: HomePresentationLogic {
  weak var viewController: HomeDisplayLogic?

  func presentError(_ error: Error) {
    viewController?.displayError(error)
  }

  func presentBanners(response: Home.FetchBanner.Response) {
    let displayedBanners = response.banners.compactMap { Home.FetchBanner.DisplayedBanner(stringUrl: $0.imageUrl) }
    let viewModel = Home.FetchBanner.ViewModel(displayedBanners: displayedBanners)
    viewController?.displayBanners(viewModel: viewModel)
  }
}
