//
//  HomeModels.swift
//  Lodjinha
//
//  Created by Gilson Gil on 22/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
  enum FetchBanner {
    struct DisplayedBanner {
      let stringUrl: String
    }

    struct Request {}
    struct Response {
      let banners: [Banner]
    }
    struct ViewModel {
      let displayedBanners: [DisplayedBanner]
    }
  }
}
