//
//  AboutViewController.swift
//  Lodjinha
//
//  Created by Gilson Gil on 27/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AboutDisplayLogic: class {
  func displayInfo(viewModel: About.GetInfo.ViewModel)
}

final class AboutViewController: UIViewController {
  var interactor: AboutBusinessLogic?
  var aboutView: AboutViewLogic?

  // MARK: - Object lifecycle

  init() {
    super.init(nibName: nil, bundle: nil)
    setup()
  }

  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }

  // MARK: - Setup

  private func setup() {
    let viewController = self
    let interactor = AboutInteractor()
    let presenter = AboutPresenter()
    viewController.interactor = interactor
    interactor.presenter = presenter
    presenter.viewController = viewController

    let tabBarItem = UITabBarItem(title: String.About.tabBar,
                                  image: UIImage.About.tabBarIcon,
                                  selectedImage: UIImage.About.tabBarIconSelected)
    self.tabBarItem = tabBarItem
  }

  // MARK: - View lifecycle

  override func loadView() {
    let aboutView = AboutView()
    self.aboutView = aboutView
    view = aboutView
  }

  override func viewDidLoad() {
    super.viewDidLoad()
    getInfo()
  }

  // MARK: Get Info

  func getInfo() {
    let request = About.GetInfo.Request()
    interactor?.getInfo(request: request)
  }
}

// MARK: - AboutDisplayLogic
extension AboutViewController: AboutDisplayLogic {
  func displayInfo(viewModel: About.GetInfo.ViewModel) {
    aboutView?.nameLabel.text = viewModel.name
    aboutView?.dateLabel.text = viewModel.date
  }
}
