//
//  AboutInteractor.swift
//  Lodjinha
//
//  Created by Gilson Gil on 27/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AboutBusinessLogic {
  func getInfo(request: About.GetInfo.Request)
}

protocol AboutDataStore {}

final class AboutInteractor: AboutBusinessLogic, AboutDataStore {
  var presenter: AboutPresentationLogic?

  // MARK: Get Info

  func getInfo(request: About.GetInfo.Request) {
    let devName = (Bundle.main.infoDictionary?["DeveloperName"] as? String) ?? ""
    let date = Date()
    let response = About.GetInfo.Response(name: devName, date: date)
    presenter?.presentInfo(response: response)
  }
}
