//
//  AboutModels.swift
//  Lodjinha
//
//  Created by Gilson Gil on 27/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum About {
  enum GetInfo {
    struct Request {}
    struct Response {
      let name: String
      let date: Date
    }
    struct ViewModel {
      let name: String
      let date: String
    }
  }
}
