# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ALodjinha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ALodjinha
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'Kingfisher'
  pod 'PKHUD', :git => 'git@github.com:pkluz/PKHUD.git'

  target 'ALodjinhaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ALodjinhaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
