//
//  CategoryRouter.swift
//  Lodjinha
//
//  Created by Gilson Gil on 24/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CategoryRoutingLogic {
}

protocol CategoryDataPassing {
  var dataStore: CategoryDataStore? { get }
}

final class CategoryRouter: NSObject, CategoryRoutingLogic, CategoryDataPassing {
  weak var viewController: CategoryViewController?
  var dataStore: CategoryDataStore?
}
