//
//  CategoryWorker.swift
//  Lodjinha
//
//  Created by Gilson Gil on 24/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class CategoryWorker {
  static var perPage: Int {
    return 20
  }

  func fetchProducts(categoryId: Int, page: Int, completion: @escaping (() throws -> [Product]) -> Void) {
    ALodjinhaAPI.getProducts(with: categoryId, page: page, perPage: CategoryWorker.perPage, completion: completion)
  }
}
