//
//  ProductListModels.swift
//  ALojinha
//
//  Created by Arlen on 05/05/19.
//  Copyright (c) 2019 Arlen Ricardo Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductListModel
{
  // MARK: - ProductList Models
  enum ProductsModel
  {
    struct Request
    {
    }
    struct Response
    {
        var productsResponse: [ProductAPIRequest]
    }
    struct ViewModel
    {
        struct DisplayedProductList {
            var categoryDesc: String
            var id: Int
            var name: String
            var urlImagem: String
            var descriptionBS: String
            var price1: Double
            var price2: Double
        }
        var displayersProductList: [DisplayedProductList]
    }
  }
    
    enum CategoryModel
    {
        struct Request {}
        
        struct Response {
            var categoryResponse: [CategoryAPIRequest]
        }
        
        struct ViewModel {
            struct displayerCategories {
                var idCategory: Int
                var descriptionCategory: String
                var urlImagemCategory: String
            }
            var displayerCategory: [displayerCategories]
        }
    }
}
