//
//  ProductListWorker.swift
//  ALojinha
//
//  Created by Arlen on 05/05/19.
//  Copyright (c) 2019 Arlen Ricardo Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ProductListWorker
{
  func doSomeWork()
  {
  }
}
