//
//  ProductDetailModels.swift
//  ALojinha
//
//  Created by Arlen on 06/05/19.
//  Copyright (c) 2019 Arlen Ricardo Pereira. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductDetail
{
  // MARK: Detail Model
  enum DetailModel
  {
    struct Request
    {
    }
    struct Response
    {
        var detailResponse: ProductAPIRequest
    }
    struct ViewModel
    {
        struct DisplayedProductDetail {
            var categoryDesc: String
            var id: Int
            var name: String
            var urlImagem: String
            var descriptionBS: String
            var price1: Double
            var price2: Double
        }
        var displayersProductDetail: [DisplayedProductDetail]
    }
  }
    
    // MARK: Reserve Product Model
    enum ReserveProductModel
    {
        struct Request
        {
            var idProduct: Int
        }
        struct Response
        {
            var reserveResponse: [ReserveAPIRequest]
        }
        struct ViewModel
        {
            var result: String
        }
    }
}
