//
//  RootViewController.swift
//  Lodjinha
//
//  Created by Gilson Gil on 21/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class RootViewController: UINavigationController {
  private let tabController: UITabBarController = {
    let tabController = UITabBarController()
    tabController.viewControllers = [HomeViewController()]
    return tabController
  }()

  convenience init() {
    self.init(nibName: nil, bundle: nil)
  }

  override var preferredStatusBarStyle: UIStatusBarStyle {
    return .lightContent
  }

  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    viewControllers = [tabController]
    setup()
  }

  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }

  // MARK: - Setup

  private func setup() {
    view.backgroundColor = .white
    navigationBar.barTintColor = .purple
    navigationBar.tintColor = .white
    navigationBar.titleTextAttributes = [.foregroundColor: UIColor.white]
    UITabBar.appearance().tintColor = .purple
  }
}
