# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'a-lodjinha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for a-lodjinha

  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod ‘AlamofireImage’, ‘~> 3.1’

  target 'a-lodjinhaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'a-lodjinhaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
