//
//  AboutViewControllerTests.swift
//  Lodjinha
//
//  Created by Gilson Gil on 27/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Lodjinha

import Quick
import Nimble

final class AboutViewControllerSpec: QuickSpec {
  // MARK: Subject under test
  override func spec() {
    let sut = AboutViewController()
    let window = UIWindow()
    window.rootViewController = sut
    window.makeKeyAndVisible()

    describe("given an about view controller") {
      context("when successfully loaded") {
        it("should display dev name") {
          expect(sut.aboutView?.nameLabel.text).to(equal("Gilson Gil"))
        }

        it("should display date") {
          let date = Date()
          let expectation = DateFormatter.displayDateFormatter.string(from: date)
          expect(sut.aboutView?.dateLabel.text).to(equal(expectation))
        }
      }
    }
  }
}
