source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def testing_pods
    pod 'Quick', '~> 1.3.0'
    pod 'Nimble', '~> 7.1.2'
    pod 'KIF-Quick', '~> 1.1.0'
    pod 'Nimble-Snapshots', '~> 6.7.1'
end

target 'desafiob2w' do
    pod 'R.swift', '~> 4.0.0'


    target 'desafiob2wTests' do
        inherit! :search_paths
        # Pods for testing
        testing_pods
    end

end
