//
//  HomePresenterTests.swift
//  Lodjinha
//
//  Created by Gilson Gil on 27/02/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Lodjinha

import Quick
import Nimble

final class HomePresenterSpec: QuickSpec {
  override func spec() {
    let sut = HomeViewController()
    let presenter = HomePresenter()
    presenter.viewController = sut
    let window = UIWindow()
    window.rootViewController = sut
    window.makeKeyAndVisible()

    describe("given a home presenter") {
      context("when an error occour") {
        it("should present an alert") {
          let error = ALodjinhaError.custom("Errou!")
          presenter.presentError(error)
          expect(sut.presentedViewController).toEventually(beAnInstanceOf(UIAlertController.self))
        }
      }
    }
  }
}
